schema_version = "1.0.0"

id = "dy_pack_master"
version = "1.0.0"
name = "dy Pack Master"
tagline = "Make Blender projects portable for render farms"
maintainer = "Carlos Dordelly - @cdordelly"
type = "add-on"
website = "https://github.com/cdordelly/dy_pack_master"
license = ["SPDX:GPL-3.0-or-later"]
blender_version_min = "4.2.0"
tags = ["Pipeline", "Import-Export", "System"]

[permissions]
files = "All" # We need full file access to copy assets anywhere